### ISSUE TITLE
MOE Plugin crashing Android Studio

### ISSUE THREAD

**Issue by angyay0** [multi-os-engine/multi-os-engine#10]
I'm using OS X El capitan. All steps to install finish correctly after execution of moe_install.sh.
Then when i try to use Android Studio the module crashes and Androis Studio restarts. 
And i'm not able to use MOE.

### My environment specs are:
*  OS X El Capitan (10.11.6)
*  Android Studio 2.1.3
*  JRE/JDK 1.8

**Comment by asuhov** [comment]
Is there any error message in the Android Studio after crash?

**Comment by angyay0** [comment]
Yes, just once. It never shows again. 
The message was something like this: 

> The plugin is not working. Disabling moe plugin. A restart would be required.

Then Android studio restarts.
 I'm trying to reproduce this error, so, when i get the message again, i'll take a screenshot.

**Comment by kisg** [comment]
Can you please test this build: https://discuss.multi-os-engine.org/t/experimental-try-out-the-new-sdk-today/60

**Comment by angyay0** [comment]
The problem was solved. Thanks.

There was a problem with designer's plugin, the error message was showed, it was a permission error. So, i changed them and it works!
