### ISSUE TITLE
application in simulator hangs if outputs messages bigger than 4096

### ISSUE THREAD

**Issue by kisg** [multi-os-engine/multi-os-engine#117]
Copied from: https://github.com/multi-os-engine/moe-ios-simulator-launcher/issues/1

as example -- application crash outputs lot of text that causes app to hangs (waiting for pipe available back)

it looks related to NSFileHandle, if replaced to separate thread with select/read pipes work.

there is my temporal workaround
https://github.com/dkimitsa/moe-ios-simulator-launcher/commit/780cdf9fb7adc0e573e0546a972360767cbf2ba7

**Comment by Noisyfox** [comment]
ios-simulator-launcher no longer used
