### ISSUE TITLE
Can't set up run configuration in IntelliJ IDEA

### ISSUE THREAD

**Issue by JBYoshi** [multi-os-engine/multi-os-engine#128]
When I try to create a Multi-OS Engine run configuration using the LibGDX template project, the module list in the run configuration editor is empty. IntelliJ gives me the following error: https://gist.github.com/JBYoshi/db9407508e6feb7f619838686e9f7b87

Steps to reproduce:

- Download and run the LibGDX setup program from https://libgdx.badlogicgames.com/download.html
- Uncheck all the checkboxes, but check the ios-moe box
- Set the project directory to an empty directory
- Click Generate
- Open the generated project
- Try to add a Multi-OS Engine run configuration

Expected result: No errors appear, and the ios-moe module appears in the run configuration editor
Actual result: The module selector is empty. When closing the editor, an error appears in the bottom-right corner of the IntelliJ IDEA window.

**Comment by Noisyfox** [comment]
Should have been fixed with latest gradle plugin and intellij plugin.
