### ISSUE TITLE
Android Studio 3.4.1 with MultiOS Engine Plugin v 1.4.3

### ISSUE THREAD

**Issue by m1imueller** [multi-os-engine/multi-os-engine#129]
After updating Android Studio to Version 3.4.1 (MAC) the context Menu with the Multi-OS Engine actions are all the time disabled. Also the Run configurations are not working.
Using the Gradle Task moeLaunch is still working.

**Comment by Noisyfox** [comment]
Should have been fixed with latest gradle plugin and intellij plugin.
