### ISSUE TITLE
[Linux] Android Studio Gradle sync issue

### ISSUE THREAD

**Issue by GMatrixGames** [multi-os-engine/multi-os-engine#132]
When creating a MOE module in the same project as the android app, when syncing the ios project it errors out with: `* What went wrong:
A problem occurred evaluating project ':ios'.
> org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V`

And the line that supposedly is causing the issue is: `apply plugin: 'moe'`

Thanks!

**Comment by Noisyfox** [comment]
MOE does not support Linux.
