### ISSUE TITLE
Discussion forum down

### ISSUE THREAD

**Issue by SlothDevLlama** [multi-os-engine/multi-os-engine#133]
Hi there folks!

Does anyone else experience the forum being not reachable at the moment?
My CI-script also fails currently, since the moe sdk dependency cannot be resolved.

Thanks!

**Comment by kisg** [comment]
Hi, 

Thanks for the report. I just restarted the forum software, should be fine now.
I just checked the bintray account, the moe packages seem to be there and fine. Could you post the detailed stacktrace of the problem you see?

Thanks,
Gergely

**Comment by TheWhiteLlama** [comment]
Thanks perfect! I double checked the other issue and it was about a week ago, probably it turned out to be a connection reset for another kind of reason.

At least, thank you for your quick actions!
