### ISSUE TITLE
Framework Not Found: MOE.framework

### ISSUE THREAD

**Issue by HeinousGames** [multi-os-engine/multi-os-engine#134]
I think I have a unique bug that has been tormenting me for almost a year, and I believe it started within the original MOE repo and is still here to this day in the forked community version. I need some dedicated help in trying to fix this issue because it has prevented me from updating past the original MOE plugin version 1.4.2.

Specs:
- Plugin: org.multi-os-engine:moe-gradle:1.4.2
- Android Studio 3.3
- MacOS 10.15.2
- Xcode 10.3
- iPhone SE running 13.3

Notes:
- Trying to use versions 1.4.3 or 1.4.4 of the original plugin result in the framework not found error when trying to build to a device. If I can't build to a device, I can't release, so I have been stuck with version 1.4.2. Oddly enough, I can successfully build and run on a simulator.
- Community plugin version 1.4.6 had worked the first day I tried it, then started showing the same framework missing error again after a computer restart.
- Community plugin versions 1.4.7 and 1.4.8 Snapshot also did not work.
- I can also successfully run the app on a simulator with any version of the community plugin.

Hypothesis:
I think that the original moe team introduced this bug to the MOE.framework file when transitioning between 1.4.2 and 1.4.3. I have seen some notes online regarding creating frameworks and how if it is done incorrectly, it may not work for both devices and simulators  (ie https://stackoverflow.com/questions/40516568/swift-framework-build-fails-for-device-but-not-for-simulator). Sadly, I am not experienced enough to know if this is truly the case, and since the framework seems to work for other users, it's even harder to tell. Maybe it could be the architecture for my physical device isn't supported?

I want to update and utilize the newest Android Studio and Xcode features but I'm stuck. I can't open my game's Xcode project if I already closed it. I must restart my computer before I can reopen the project in Xcode again. Using these old versions is a nightmare, please help!

**Comment by kisg** [comment]
Thank you for the detailed report. We are in the process of preparing the 1.5.0 release of MOE, we will make sure that this problem is fixed.

**Comment by HeinousGames** [comment]
@kisg Thank you very much! If you need any additional details from me or help in testing/reporting, just let me know.

**Comment by HeinousGames** [comment]
I updated to 1.5.0 two days ago and have not run into this bug yet. I think it may be fixed, and I appreciate everyone's work involved. I will reach back out if the issue returns.
