### ISSUE TITLE
crash when getting last item from array pointer

### ISSUE THREAD

**Issue by sdyura** [multi-os-engine/multi-os-engine#138]
this crashes when i try and get last integer from array into a new array of size 1

PtrFactory.newIntArray(new int[] { 0,1,2,3,4 }).getGuarded(5).copyTo(4, new int[1], 0, 1);

in the code it says:

    @Override
    public final IntPtr getGuarded(int length) {
        return getGuarded(0, length);
    }

    @Override
    public IntPtr getGuarded(int fromIndex, int toIndex) {
        if (toIndex < fromIndex) {
            throw new IllegalArgumentException();
        }
        return new GuardedIntPtrImpl(getRoot(), this, fromIndex, toIndex);
    }

and it looks like it uses to length as the toIndex, but thats very confusing
but then it uses to toIndex as the hi number and checks as if it IS the length:

        @Override
        public boolean checkIndex(int index) {
            return index >= low && index < hi;
        }

but then when i ask for the last item, it checks the length is less then the hi, this should be ok but its not

        @Override
        public void copyTo(int srcOffset, int[] dest, int destOffset, int length) {
            if (!checkIndex(srcOffset) || !checkIndex(srcOffset + length)) {
                throw new IndexOutOfBoundsException();
            }
            super.copyTo(srcOffset, dest, destOffset, length);
        }

**Comment by Noisyfox** [comment]
Right this seems to be a bug. I'll fix this in the next release.

**Comment by Noisyfox** [comment]
This should be fixed in MOE-1.8.0
