### ISSUE TITLE
clangFirstWord() fails when property has a UpperCase letter at beginning.

### ISSUE THREAD

**Issue by Berstanio** [multi-os-engine/multi-os-engine#144]
I tried to generate bindings for a header that contained this (from a swift pod):
```ObjC
/// The current visible drop down. There can be only one visible drop down at a time.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, weak) DropDown * _Nullable VisibleDropDown;)
+ (DropDown * _Nullable)VisibleDropDown SWIFT_WARN_UNUSED_RESULT;
+ (void)setVisibleDropDown:(DropDown * _Nullable)value;
```
This fails with a StringIndexOutOfBoundsException. The cause is in the "clangFirstWord" method:
```Java
        while (loc < selector.length()) {
            char c = selector.charAt(loc);
            if (Character.isUpperCase(c) || c == ':') break; // This loop will directly break here, because the first letter is upper case. loc 
                                                                                     // will still be zero
            ++loc;
        }
```
Then it will go into this if statement:
```Java
        if (loc == 0) {
            while (loc < selector.length()) {
                char c = selector.charAt(loc);
                if (Character.isLowerCase(c) || c == ':') break; // It will break here when loc = 1.
                ++loc;
            }
            if (loc != selector.length()) --loc; // After the loop is loc equals 1. But here it will get subtracted by 1. So loc is again zero.
        }
```
So the resulting substring `return selector.substring(start, loc);` will be empty. This will result in these lines: https://github.com/multi-os-engine/moe-natjgen/blob/moe-master/src/main/java/org/moe/natjgen/ObjCMethod.java#L497-L498
in the StringIndexOutOfBoundsException.

My idea was to to implement a check in the first loop, that when the character is upper case, the loop only breaks if loc != 0. Maybe also make the first letter lower case (only for the java method name)? But I don't know enough about ObjC and Swift naming conventions etc. to know, whether this would break anything.

**Comment by Berstanio** [comment]
Btw. I think the bug was introduced here, when the default start location of "clangFirstWord" was changed to "0" from "1".
https://github.com/multi-os-engine/moe-natjgen/commit/341d93b583856b241f6391993605c51f13676ac0

**Comment by Noisyfox** [comment]
Yeah a good catch here. I don't think this will break anything, as the `clangFirstWord` method is only used to determine whether the method is a alloc/init/copy method, and if the method starts with an uppercase letter then it's definitely not one of those. I'll fix this.

**Comment by Berstanio** [comment]
I tested the the fix and it works fine! Thanks for fixing this! So I think this should be closed.
