### ISSUE TITLE
Used frameworks do not loaded automatically on iOS simulator

### ISSUE THREAD

**Issue by sdyura** [multi-os-engine/multi-os-engine#153]
when i try and run this method i get an exception

/Users/noisyfox/Documents/project/moe/moe/natj/natj/src/main/native/natj/ObjCRuntime.mm:1480 WARNING: Binding class refers to class MFMailComposeViewController, but it can not be found. Fallback to indirect super class.
2021-12-22 23:03:57.994 Domination[20487:707237] +[UINavigationController canSendMail]: unrecognized selector sent to class 0x7fff864ac6b8

this method works fine on an actual device, but its annoying that it cant just return false on the simulator

**Comment by Noisyfox** [comment]
Make sure you have `MessageUI.framework` added 
![image](https://user-images.githubusercontent.com/1537155/147174985-6fcd9873-bfb2-41ca-9047-3043f8114a1a.png)

**Comment by sdyura** [comment]
that fixed the issue.

how do I know when i need to do this?
in the example apps they make use of many frameworks and yet they do not list them
(e.g. Planets uses CoreGraphics.framework but does not need to add it to the list)

if it is missing a framework, could it throw an error that is more helpful, and tells me what i need to do to fix it

thanks

**Comment by Noisyfox** [comment]
If you view the source of the `MFMailComposeViewController` you will see an annotation `@Library("MessageUI")`, which means it's from the framework and you should add it to the list.

There are some frameworks like `UIKit` or `CoreGraphics` or `Foundation` or `CoreFoundation` that are used by MOE which will be included transitively so you don't need to explicitly add them (but you should, just in case MOE no longer use them later and your app suddently breaks).

> if it is missing a framework, could it throw an error that is more helpful, and tells me what i need to do to fix it

I think I can improve the error message to tell you which framework to add. I might also add a compile time warning as well.

**Comment by Noisyfox** [comment]
I realized this is actually a bug in the NatJ. On iOS it can automatically load the required framework, so you don't need to include this in that list, however that code does not work properly on simulator.

I'll fix that, for now you just need to include the used framework manually.

**Comment by Noisyfox** [comment]
The latest 1.9 SNAPSHOT should've fixed this issue.
