### ISSUE TITLE
Backport Java 8 features using desugar_jdk_libs & ProGuard

### ISSUE THREAD

**Issue by Noisyfox** [multi-os-engine/multi-os-engine#154]
https://github.com/google/desugar_jdk_libs

ProGuard is able to process classes under `java.*` package, so it migth be possible to backporting some Java 8 runtime classes to current ART runtime.

If this is not possible, then we could just use ProGuard's own backport with `net.sourceforge.streamsupport` and `org.threeten`
https://www.guardsquare.com/manual/configuration/usage#target

**Comment by Noisyfox** [comment]
One issue found using this approach. 
https://github.com/Guardsquare/proguard/issues/210

**Comment by sdyura** [comment]
is  https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html going to be supported? i think it is not there now

**Comment by Noisyfox** [comment]
> is https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html going to be supported? i think it is not there now

Interesting, I didn't notice this was missing. I'll see if it can be added.

**Comment by Noisyfox** [comment]
I find it very difficult to backport the `java.nio.file` package because those are not available in desugar_jdk_libs.

**Comment by sdyura** [comment]
can you just use the macOS openJDK version?

android ( https://developer.android.com/reference/java/nio/file/Files ) and desktop JRE both have this class, so it would be useful to also have it in MOE as then i can write code that uses it and runs everywhere

**Comment by Noisyfox** [comment]
It's virtually impossible to use the runtime library from other JDKs, without heavy modifications. The only feasible solution is to use the jdk11 runtimes from `desugar_jdk_libs` which I'm trying to do, but this won't be easy as it requires porting some other jdk11 APIs.

**Comment by Noisyfox** [comment]
The latest snapshot should have `java.nio.file` support, however it's not guaranteed that everything will work properly, as I don't have a way to properly test every single APIs.

**Comment by sdyura** [comment]
thanks! i have tested the method i wanted to use ( Files.probeContentType() ) and it is working for me!

**Comment by sdyura** [comment]
FYI
you said in your commend that you are going to get some java11 APIs, i tried:
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Files.html#readString(java.nio.file.Path)
and it said it could not find that method

(not really a problem for me)

**Comment by Noisyfox** [comment]
Are you sure the project SDK is set to JDK 11 in intellij?

**Comment by Noisyfox** [comment]
Some more missing pieces that can be added:
https://discuss.multi-os-engine.org/t/error-with-version-1-8-2/2914/8?u=noisyfox

**Comment by sdyura** [comment]
i seem to not be able to use the class:
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html
anywhere, tried 1.9.1-SNAPSHOT

error: cannot find symbol class CompletableFuture
java.lang.NoClassDefFoundError: Ljava/util/concurrent/CompletableFuture;

**Comment by Noisyfox** [comment]
> i seem to not be able to use the class: https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html anywhere, tried 1.9.1-SNAPSHOT
> 
> error: cannot find symbol class CompletableFuture java.lang.NoClassDefFoundError: Ljava/util/concurrent/CompletableFuture;

Yeah this class has not been backported yet. I'll add this soon.
