### ISSUE TITLE
Deprecated iOS values not shown as Deprecated in java

### ISSUE THREAD

**Issue by sdyura** [multi-os-engine/multi-os-engine#157]
i am used to just looking at the API from AndroidStudio and just looking at the java one, and when it all looks good e.g. UIStatusBarStyle.BlackOpaque i feel ive found the right thing and i move on, then it can take me a long time to realize that i have actually used the wrong thing, and https://developer.apple.com/documentation/uikit/uistatusbarstyle/uistatusbarstyleblackopaque?language=objc is actually deprecated and replaced by a new value, and all this time i am scratching my head trying to work out why the app keeps doing unexpected things

**Comment by Noisyfox** [comment]
This should be solved now.
