### ISSUE TITLE
detect if debug build from java without any obj-c code

### ISSUE THREAD

**Issue by sdyura** [multi-os-engine/multi-os-engine#159]
i have been working with MOE for a few months and managed to write a whole game in java using the apple API, and i love the fact ive not had to learn any new language syntax, and ive been able to do everything i can dream of in java, everything except one thing, detect if this is a debug build, ive been told that this is really simple:

"You could write a small function in ObjC that returns different value with "#ifdef DEBUG", then call this from your Java code."

but considering i have never written any ObjC, have no idea where to put the file, what to put into the file, or how to then call it from java, things ive never needed to do so far, i would actually need to learn quite a lot to do this simple task.

also swift and kotlin has "Platform.isDebugBinary" so java should have a method too!

there are many workaround for this, but its always going to be easier to just have a nice method to call

**Comment by sdyura** [comment]
another thing that could also be really useful and not really possible to currently do without obj-c code is having a method that returns if the app is running on a iOS Simulator.

in swift you can do

#if targetEnvironment(simulator)

but as java does not have the #if command, it would be good to be able to call a normal method for

isTargetSimulator

**Comment by Noisyfox** [comment]
> another thing that could also be really useful and not really possible to currently do without obj-c code is having a method that returns if the app is running on a iOS Simulator.
> 
> in swift you can do
> 
> #if targetEnvironment(simulator)
> 
> but as java does not have the #if command, it would be good to be able to call a normal method for
> 
> isTargetSimulator

Yes that's also in my mind. Actually this will be easier than checking if it's debug build, as simulator build will be linked to a different MOE framework, so this check can be baked inside the MOE framework, while the debug check need to happen when the app itself is built.

**Comment by Noisyfox** [comment]
My current idea is splitting the current `moevm` function (https://github.com/multi-os-engine/moe-core/blob/ecca888c9b7c30a129ad943a06bdab88dd7f3128/moe.apple/moe.core.native/moe.sdk/src/MOE.mm#L75) into two functions: `moevm_release` and `moevm_debug`, which will define a `MOE_DEBUG` environment variable before calling the real `moevm` function, i.e.,:

### MOE.mm:
```objc
int _moevm(const int jargc, char* const* jargv) {
    // The existing moevm function
}

extern "C" int moevm_release(const int jargc, char* const* jargv) {
    setenv("MOE_DEBUG", "false", true);  // Set debug env variable to false
    return _moevm(jargc, jargv); // Call the actual moevm
}

extern "C" int moevm_debug(const int jargc, char* const* jargv) {
    setenv("MOE_DEBUG", "true", true);  // Set debug env variable to true
    return _moevm(jargc, jargv); // Call the actual moevm
}
```

Then in the header (https://github.com/multi-os-engine/moe-core/blob/ecca888c9b7c30a129ad943a06bdab88dd7f3128/moe.apple/moe.core.native/moe.sdk/src/MOE.h) we define the macro `moevm` to `moevm_release` or `moevm_debug` based on whether it's debug build or not:
### MOE.h:
```objc
#ifdef DEBUG
EXTERN int moevm_debug(const int jargc, char *const *jargv);
#define moevm moevm_debug
#else
EXTERN int moevm_release(const int jargc, char *const *jargv);
#define moevm moevm_release
#endif
```

Then in Java we could have a method that reads this environment variable to check if it's debug or not.
```java
public static boolean isDebug() {
    return "true".equals(System.getenv("MOE_DEBUG"));
}
```

**Comment by Noisyfox** [comment]
This is the easiest way I could think of without the need of updating any of the user project files.

However since MOE 1.9 requires an update to the xcode project file, this is not really a problem. We can of course add a function like this to the `main.cpp` file (or a separate file):
```cpp
__attribute__((visibility("default"))) int is_debug() {
#ifdef DEBUG
    return 1;
#else
    return 0;
#endif
}
```
then call this function from java, but this solution needs either:
- Ask user to manually add this to their existing project
- or updating the gradle plugin to add this

and both require more effort.

**Comment by sdyura** [comment]
i thought you were going to put that thing you mentioned 'ObjC that returns different value with "#ifdef DEBUG" ' into the existing generated obj-c file moe-main-interfaces.m thats showing up as part of the project, i dont really understand what the file does.

regenerating project files is totally fine, especially if it makes the code simpler

and if java having a method or env variable are both perfect

**Comment by Noisyfox** [comment]
Another solution is to generate a config file that will be bundled into the app during the build process, which contains the debug flag, then read this file in Java. The benefits is we can add more build-time configs in it later, but the downsides are:
- More codes
- Require updating project file
- Could lead to inconsistency between Java & native codes (for example if you removed the `DEBUG` macro from the Xcode debug config, which will only affect the native codes but not the Java part)

**Comment by Noisyfox** [comment]
> i dont really understand what the file does.

This allows you to use interface builder with the ViewControllers you created in Java.



> into the existing generated obj-c file moe-main-interfaces.m

I'd prefer to put this method in a read-only files, as in some of my project I disabled the generation of this file.

**Comment by Berstanio** [comment]
> Then in Java we could have a method that reads this environment variable to check if it's debug or not.
> 
> ```java
> public static boolean isDebug() {
>     return "true".equals(System.getenv("MOE_DEBUG"));
> }
> ```

Have you tested this? I remember that in the standard JRE ```System.getenv()``` sometimes works a bit strange and isn't able to fetch a env variable that was updated with ```setenv``` after the process was started. So maybe a java native method is needed that runs getenv.

**Comment by Noisyfox** [comment]
> > Then in Java we could have a method that reads this environment variable to check if it's debug or not.
> > ```java
> > public static boolean isDebug() {
> >     return "true".equals(System.getenv("MOE_DEBUG"));
> > }
> > ```
> 
> Have you tested this? I remember that in the standard JRE `System.getenv()` sometimes works a bit strange and isn't able to fetch a env variable that was updated with `setenv` after the process was started. So maybe a java native method is needed that runs getenv.

The environment variable will be set BEFORE the JVM is started so it can work. We are doing similar thing already (https://github.com/multi-os-engine/moe-core/blob/ecca888c9b7c30a129ad943a06bdab88dd7f3128/moe.apple/moe.core.native/moe.sdk/src/MOE.mm#L120-L131).

**Comment by Noisyfox** [comment]
`DEBUG`, `IS_SIMULATOR` flags are added to class `org.moe.MOE.Build`
