### ISSUE TITLE
Support new proxy config format from GraalVM 22.x

### ISSUE THREAD

**Issue by Noisyfox** [multi-os-engine/multi-os-engine#163]
https://www.graalvm.org/22.0/reference-manual/native-image/DynamicProxy/#manual-configuration

From GraalVM 22.0 the proxy config format has been updated from
```json
[
    ["java.lang.AutoCloseable", "java.util.Comparator"],
    ["java.util.Comparator"],
    ["java.util.List"]
]
```
to
```json
[
 { "interfaces": [ "java.lang.AutoCloseable", "java.util.Comparator" ] },
 { "interfaces": [ "java.util.Comparator" ] },
 { "interfaces": [ "java.util.List" ] }
]
```

We should support both format, by passing the GraalVM version to the proxy collector.

~~Also we may want to add a proxy config transformer, so that the proxy-base-config file can be written in latest format then be used by both old and new GraalVM versions.~~

**Comment by Berstanio** [comment]
> Also we may want to add a proxy config transformer, so that the proxy-base-config file can be written in latest format then be used by both old and new GraalVM versions.

I think there is no need to do that for the base config file. It was a mistake by mine to add this file in the first place, since there is no proxy config needed for a minimal app and also the defined proxy there would be automatically collected.
