### ISSUE TITLE
Make sure static interface methods in SDK are backported properly

### ISSUE THREAD

**Issue by Noisyfox** [multi-os-engine/multi-os-engine#169]

**Comment by Noisyfox** [comment]
This can be done by running the backport as a separate step after proguard, i.e., run proguard twice, which:
1. Do shrinking & obfuscating as configured, with proper proguard level
2. Then run proguard with everything disabled except backporting, with everything (i.e., both app code and MOE core/ios jars) as inputs.

This will make the build time longer, as now no pre-desugaring can be made to MOE core and iOS jars, but this also reduces the SDK size as we no longer need to ship the pre-dexed cores.

**Comment by Berstanio** [comment]
I think this is already fully implemented.
