### ISSUE TITLE
Support binding to frameworks that are split from other frameworks

### ISSUE THREAD

**Issue by Noisyfox** [multi-os-engine/multi-os-engine#181]
https://discuss.multi-os-engine.org/t/unsupported-ios-sdk-after-updating-to-moe-1-9-0/2922

`AVFAudio` was split from `AVFoundation` framework, and it does not exist prior to iOS 14.5+. On those systems, the symbols from `AVFAudio` are actually provided by the old `AVFoundation` framework. And on iOS 14.5+, those symbols are defined in `AVFAudio` headers, and reexported by `AVFoundation` framework headers.

When we load the bindings for `AVFAudio`, we should first try loading `AVFAudio` framework, and if it does not exist, then fallback to `AVFoundation` framework instead.

**Comment by Noisyfox** [comment]
My current thought is to extend the `org.moe.natj.general.ann.Library` to include an optional fields that contains a list of libraries to fallback to, if the primary one does not exist.

**Comment by Noisyfox** [comment]
Hmmm now I think this might not be a good idea because that means I'll need to update every single binding files from that framework, and if one missed could cause problems. I think I'll go with your solution from https://github.com/multi-os-engine/moe-natj/pull/4 but maybe having a global registry/look up table to generalise these kind of situations (and maybe also allow devs to add their own fallbacks).

**Comment by Berstanio** [comment]
> but maybe having a global registry/look up table to generalise these kind of situations

Sounds like a good idea, should I extend my pr?

> and maybe also allow devs to add their own fallbacks

Is probably nothing that hurts to have, but I can't imagine a situation where custom fallbacks would be needed. Aren't the only cases where this could happen related to the iOS SDK and therefor should be handled inside the moe sdk?
