### ISSUE TITLE
Multiple inheritance on MOE bindings not working when overriding method with annotations only in the last class

### ISSUE THREAD

**Issue by Berstanio** [multi-os-engine/multi-os-engine#182]
Proguard desugaring seems to have a bug with default methods and parameter annotation. Lets assume we have class "TestClass1" with:
```java
import apple.uikit.protocol.UIApplicationDelegate;

public class TestClass1 implements UIApplicationDelegate {
}

```
Than proguard desugars the default methods of UIApplicationDelegate by copying them to TestClass1. But on default methods with parameter annotations, proguard emits a empty ParameterAnnotations section:
(with javap you will see on a example code)
 ```
    RuntimeInvisibleAnnotations:
      0: #103()
        org.moe.natj.general.ann.Generated
    RuntimeVisibleAnnotations:
      0: #108()
        org.moe.natj.objc.ann.IsOptional
      1: #110(#276=s#150)
        org.moe.natj.objc.ann.Selector(
          value="application:performFetchWithCompletionHandler:"
        )
    RuntimeVisibleParameterAnnotations:
```
However, this is incorrect! It should either be no ParameterAnnotations section at all, or:
```
    RuntimeInvisibleAnnotations:
      0: #103()
        org.moe.natj.general.ann.Generated
    RuntimeVisibleAnnotations:
      0: #108()
        org.moe.natj.objc.ann.IsOptional
      1: #110(#276=s#150)
        org.moe.natj.objc.ann.Selector(
          value="application:performFetchWithCompletionHandler:"
        )
    RuntimeVisibleParameterAnnotations:
      parameter 0:
      parameter 1:
```
Even this is broken bytecode, dx/dex2oat seems to still process it.

When we than have another class "TestClass2" with the following:
```java
import apple.uikit.UIApplication;

public class TestClass2 extends TestClass1 {
    @Override
    public void applicationPerformFetchWithCompletionHandler(UIApplication application,
            Block_applicationPerformFetchWithCompletionHandler completionHandler) {
    }
}
```

Now when the classvalidator runs after the desugaring, it tries to copy the annotations from the parent implemenation. But since java is more strict, a "java.lang.annotation.AnnotationFormatError: Parameter annotations don't match number of parameters" exception is thrown.

Also, I don't know whether or when you plan to merge/take a look at the r8 stuff, but that should also fix the issue.

**Comment by andre719mv** [comment]
In my case function was defined in TestClass1, but it was defined as abstract. Adding of missed annotations did not help. Fix that worked for me:
![image](https://github.com/multi-os-engine/multi-os-engine/assets/22563994/f5de20c5-ae55-4abb-a7b1-dbeb84d03511)

**Comment by Berstanio** [comment]
Fixed in https://github.com/multi-os-engine/proguard-core/commit/52f9cf2070441d17bc791133730f882e5af7eb08
