### ISSUE TITLE
method setNeedsUserInterfaceAppearanceUpdate seems to be missing

### ISSUE THREAD

**Issue by sdyura** [multi-os-engine/multi-os-engine#191]
the setNeedsUserInterfaceAppearanceUpdate method does not seem to come up

apple doc says this method was added in iOS 11:

https://developer.apple.com/documentation/uikit/uiviewcontroller/2909094-setneedsuserinterfaceappearanceu

as a workaround you can call this method with

`performSelector(new SEL("setNeedsUserInterfaceAppearanceUpdate"));`

**Comment by Berstanio** [comment]
The doc you linked says it is only "tvOS 11+", or am I missing something?

**Comment by sdyura** [comment]
you are right, it seems to exist on a iPhone but i guess it is not used
