### ISSUE TITLE
System.setProperty("java.io.tmpdir", myTempDirectory); regression in MOE 1.10.0

### ISSUE THREAD

**Issue by sdyura** [multi-os-engine/multi-os-engine#198]
in java you should be able to set the System property for "java.io.tmpdir"

this works on desktop java and on android, and also used to work fine on MOE 1.9.0
but this seems to be broken on 1.10.0

**Comment by Berstanio** [comment]
What exactly is failing?
According to the documentation, some methods that use the tempdir property are not guarantee that `System.setProperty` for `java.io.tmpdir` has any effect on them:

> A different value may be given to this system property when the Java virtual machine is invoked, but programmatic changes to this property are not guaranteed to have any effect upon the temporary directory used by this method.

Source: https://docs.oracle.com/javase/8/docs/api/java/io/File.html for `createTempFile`

The change of behaviour you see was introduced by fixing https://github.com/multi-os-engine/multi-os-engine/issues/183
Is there still a use case to set `java.io.tmpdir`?

**Comment by sdyura** [comment]
**setting** the value is breaking, you should be able to override the default value, you can do on all other platforms, and you could override the default value in MOE-1.9.0

its a feature that is useful when you want to change where some lib saves its temp files
i know some methods do not guarantee that changing the value will affect them, but other methods DO get affected, for example if some lib is getting that value, and its the methods that used to get affected that i want to keep being able to affect.

`createTempFile` does not need to get updated, it can ignore the user override as per docs. but it should Not reset the user set value, so after calling it, the user set value should still be the same.

I need to be able to set the value, so when the value is read with `getProperty("java.io.tmpdir")`, it is the new one
