### ISSUE TITLE
File.listRoots()[0].getFreeSpace()/getTotalSpace()/getUsableSpace() returns totally incorrect result

### ISSUE THREAD

**Issue by sdyura** [multi-os-engine/multi-os-engine#200]
i have a lib that uses the result of this call to decide what to do

`File.listRoots()[0].getFreeSpace()`

on my 128GB iPhone this call returns "`24536404721664`"bytes (24536.4 GB)

this is clearly incorrect and stops the lib from functionating properly

i have also tried `File.listRoots()[0].getTotalSpace()` returns `32762619756544`

and `File.listRoots()[0].getUsableSpace()` returns `24535761944576`

all of these numbers seem to be vastly incorrect for my 128GB iPhone

i have tested this on MOE 1.9.0 and MOE 1.10.0 and BOTH versions are broken

**Comment by Berstanio** [comment]
This seems to be due to a broken (?) implementation of statvfs on iOS. It returns an incorrect block size:
```
Free-Blocks statfs: 8586372 Block-Size statfs: 4096
Free-Blocks statvfs: 8586372 Block-Size statvfs: 1048576
```
Switching to statfs should be feasible tho
