### ISSUE TITLE
Linux host support

### ISSUE THREAD

**Issue by kisg** [multi-os-engine/multi-os-engine#34]
Support developing iOS apps on Linux using the remote build feature

**Comment by sluedecke** [comment]
Well at least I can get the sample CurrencyConverter running on a Linux host on an Android emulator without any trouble.  I just had to set the

`` classpath group: 'org.multi-os-engine', name: 'moe-gradle', version: '1.1.+'

in the ios module of the samples.  I did not test the remote compile function.

**Comment by sluedecke** [comment]
I had some more success.

Calling the command line, I was able to use the moeConfigRemote target and some manual editing of the resulting `ios/moe.remotebuild.properties` and can do some things on a remote build machine.

Unfortunately it has Xcode 8 and I hit the same error as mentioned here: https://discuss.multi-os-engine.org/t/project-doesnt-work-with-xcode-8/169

**Comment by sluedecke** [comment]
Tried it on a different mac with xcode 7 and it compiles using `moeLaunch`.

Still it does not launch the app on my local Linux machine but I get something usable.

If I only could launch the app in a simulator on the remote macos ....

Things I did differently from the setup guideline:

- created a passwordless RSA (ed25519 is not supported by moe) SSH key on my Linux machine
- did not use separate keychain (somehow it did not become unlocked properly, probably my fault) but the login keychain
