### ISSUE TITLE
Retrofit with OkHttp crashes with SIGPIPE when returning from lock screen

### ISSUE THREAD

**Issue by muvixalex** [multi-os-engine/multi-os-engine#36]
When using Retrofit with OkHttp, when locking the screen on a real device (iPhone 5s, iOS 9.3.4) with the power button, and then unlocking the screen, the app sometimes (often) crashes with SIGPIPE.

I'm working on a repo case, in the meantime, did you encounter this before? Do you have a workaround?

Thanks,
Alex.

**Comment by liliomk** [comment]
Dear Alex,

This is an iOS behavior (I'm not even sure it's considered a bug). A workaround that may help:

1. Have `generateProject false` set
2. Add signal handling

```cpp
#include <MOE/MOE.h>
#include <signal.h>

int main(int argc, char *argv[]) {
    signal(SIGPIPE, SIG_IGN);
    return moevm(argc, argv);
}
```

**Comment by muvixalex** [comment]
I tried this, it doesn't help.

**Comment by muvixalex** [comment]
Oh, actually it does help. I just saw that the debugger still breaks on the sigpipe, so I thought it still crashes, but actually it continues to run.

But if we ignore this signal, will retrofit/okhttp know that an error occured so we can retry or act accordingly?

**Comment by muvixalex** [comment]
Seems to work well.
Thanks.
