### ISSUE TITLE
GUI editor not working on 1.1.0

### ISSUE THREAD

**Issue by jirungaray** [multi-os-engine/multi-os-engine#38]
When trying to create an iOS GUI design with the Android Studio Plugin I get an error popup saying only "0" . Editor also doesn't open when clicking on existing ixml files. 

Working on MAC OSX 10.11.6
Android Studio : 2.2 Beta 3

**Comment by kisg** [comment]
Support thread on the forum: https://discuss.multi-os-engine.org/t/problems-with-moe-ui-designer-and-xcode-ui-design/99

**Comment by jirungaray** [comment]
update: issue is also present on the stable version of Android Studio 2.1.2.

**Comment by kisg** [comment]
GUI editor was retired in MOE 1.2. More information: https://multi-os-engine.org/blog/2016-09-30-removed-features/
