### ISSUE TITLE
Swift interoperability

### ISSUE THREAD

**Issue by adi1133** [multi-os-engine/multi-os-engine#39]
I am interested in gradually migrating a project from Swift to MOE. A good way to begin could be by building an iOS framework using MOE and including it as a dependency in my existing projects.

I found a relevant topic [here](https://software.intel.com/en-us/forums/multi-os-engine/topic/625026) but I want to spark a discussion over this on github.

I am also interested in other ways to achieve Swift <-> MOE interoperability.

**Comment by kisg** [comment]
This is a very interesting topic. For such discussions we recommend using our forums: https://discuss.multi-os-engine.org
Could you please open a topic there?

**Comment by kisg** [comment]
Let's move this to the forums to discuss, and open concrete feature issues here when we have a clear plan to implement
