### ISSUE TITLE
can't access forum through https://discuss.multi-os-engine.org or http://discuss.multi-os-engine.org

### ISSUE THREAD

**Issue by radxe** [multi-os-engine/multi-os-engine#62]
Hello, I can't access forum through https://discuss.multi-os-engine.org or http://discuss.multi-os-engine.org.
What had happened?
Thanks!

**Comment by kisg** [comment]
GlobalSign messed up its intermediate CAs, and we were using AlphaSSL that was affected. I reconfigured the site to use let's encrypt.

Please check, and reopen this issue if the problem persists.
