### ISSUE TITLE
Runtime issue using jackson-databind

### ISSUE THREAD

**Issue by kevin-vf** [multi-os-engine/multi-os-engine#65]
I've run into a strange issue trying to use jackson in a MOE project. When using a simple JsonProperty annotated kotlin class, jackson will fail at runtime with a null pointer exception. However, any attempt to place a breakpoint in the function where the exception occurs causes the error to not occur. If you run the debugger with no breakpoints, it will fail just as if running the application normally.

Note that this is the most basic use of jackson possible (serializing a simple object with a single property), and it does work both on desktop platforms and android. This is just the simplest way to reproduce the bug I encountered while testing MOE with a larger application. So I assume this is not (directly) a jackson bug.

I'm using IDEA 2016.1 with the 1.2.1 MOE plugin, and the project is using MOE 1.2.4, tested on an iPad running iOS 9.1. Using the moeLaunch gradle task directly doesn't change the outcome (unsurprisingly since the IDE runs the task anyways). 

I've pushed the example code to reproduce the bug at https://github.com/kevin-vf/moe-jackson-bug This is the just the generated single view project code (converted to kotlin), with the code to trigger the bug in Main::applicationDidFinishLaunchingWithOptions.

I put a custom proguard.cfg to rule out proguard from somehow being the cause by keeping all possible classes, but it doesn't change the outcome. You can remove it and put some reference to the installationId field in the code or a proguard rule to avoid it being removed and the error will still occur.

**Comment by kisg** [comment]
Thank you for the detailed bug report, we are looking into it

**Comment by kisg** [comment]
Found the issue, it was a bug in the arm64 code generator, will release a hotfix for it next week.

**Comment by kevin-vf** [comment]
That's good to hear, looking forward to it. The app we were looking at using MOE for was highly dependent on jackson, so running into that was kind of a showstopper, glad you were able to fix it.

**Comment by kevin-vf** [comment]
I can confirm this is no longer an issue on 1.2.5. Closing issue.
