### ISSUE TITLE
Native calls to UIPopoverPresentationControllerDelegate instance result in application crash

### ISSUE THREAD

**Issue by kevin-vf** [multi-os-engine/multi-os-engine#70]
When I try to set a delegate on a UIPopoverPresentationController, any invocations on the delegate from the native end of the application result in a crash, which results in the following stacktrace:

MoePopoverDelegate[372:141967] *** Terminating app due to uncaught exception 'java.lang.RuntimeException', reason: 'java.lang.RuntimeException: Java reference construction error!
	at org.moe.natj.general.map.ReferenceMapper.toJava(ReferenceMapper.java:118)
	at org.moe.natj.general.NatJ.toJava(NatJ.java:1053)
	at apple.uikit.c.UIKit.UIApplicationMain(Native Method)
	at com.vfpowertech.moepopoverdelegate.Main$Companion.main(Main.kt:18)
	at com.vfpowertech.moepopoverdelegate.Main.main(Main.kt)
Caused by: java.lang.RuntimeException: No matching type found in ptr mapper
	at org.moe.natj.general.map.ReferenceMapper.getSimpleConstructor(ReferenceMapper.java:125)
	at org.moe.natj.general.map.ReferenceMapper.toJava(ReferenceMapper.java:67)
	... 4 more

It seems that the native side can't find a matching java object entry for the delegate object. One thing I did notice is the signature of UIPopoverPresentationController.setDelegate takes Object instead of the expected UIPopoverPresentationControllerDelegate as designated in apple's documentation for the selector signature (https://developer.apple.com/reference/uikit/uipopoverpresentationcontroller/1622320-delegate?language=objc), although I'm unsure as to whether or not this matters. I have also tried a separate object implementing only the delegate interface with the same outcome (the example project implements the interface on the view controller).

An example project which triggers this is available at https://github.com/kevin-vf/moe-popover-delegate-bug which uses MOE 1.2.5. If one runs this on an iPad, clicks the Share button to activate the popover, then rotates the device, the application will crash with the above error. It must be run on an iPad, as popovers are rendered as action sheets on other devices.

**Comment by liliomk** [comment]
Thank you for reporting this. You can work around this issue by changing:

```kotlin
    override fun popoverPresentationControllerWillRepositionPopoverToRectInView(
            popoverPresentationController: UIPopoverPresentationController,
            rect: CGRect,
            view: Ptr<UIView>)
```

to 

```kotlin
    override fun popoverPresentationControllerWillRepositionPopoverToRectInView(
            popoverPresentationController: UIPopoverPresentationController,
            rect: CGRect,
            @ReferenceInfo(depth = 1, type = UIView::class) view: Ptr<UIView>)
```

**Comment by kevin-vf** [comment]
Thanks a lot for the workaround, works like a charm.
